CREATE DATABASE  boliche
  CHARACTER SET utf8
  COLLATE utf8_unicode_ci;
GRANT SELECT,INSERT,UPDATE,DELETE ON boliche.* TO 'boliche'@'%' IDENTIFIED BY 'boliche';
GRANT SELECT,INSERT,UPDATE,DELETE ON boliche.* TO 'boliche'@'localhost' IDENTIFIED BY 'boliche';
FLUSH PRIVILEGES;
USE boliche;

CREATE TABLE  USUARIO (
  USU_ID VARCHAR(16) NOT NULL,
  USU_CONTRA VARCHAR(100) NOT NULL,
  USU_NOMBRE VARCHAR(255) NOT NULL,
  VERSION INT, /* Requerido para transacciones de JPA. */
  UPPER_ID VARCHAR(255), /* Requerido para ORDER BY de JPA. */
  CONSTRAINT USU_PK PRIMARY KEY (USU_ID),
  CONSTRAINT USU_IDCH CHECK (LENGTH(USU_ID) >= 5),
  CONSTRAINT USU_COCH CHECK (USU_CONTRA <> ''),
  CONSTRAINT USU_NOCH CHECK (USU_NOMBRE <> '')
    ) ENGINE InnoDb;

CREATE TABLE  ROL (
  ROL_ID VARCHAR(255) NOT NULL,
  ROL_DESCRIPCION VARCHAR(255) NOT NULL,
  VERSION INT, /* Requerido para transacciones de JPA. */
  UPPER_ID VARCHAR(255), /* Requerido para ORDER BY de JPA. */
  CONSTRAINT ROL_PK PRIMARY KEY (ROL_ID)
    ) ENGINE InnoDb;

CREATE TABLE  USUARIO_ROL (
  USU_ID VARCHAR(16) NOT NULL,
  ROL_ID VARCHAR(255) NOT NULL,
  CONSTRAINT UR_PK PRIMARY KEY (USU_ID, ROL_ID),
  CONSTRAINT UR_USU FOREIGN KEY (USU_ID) REFERENCES USUARIO(USU_ID),
  CONSTRAINT UR_ROL FOREIGN KEY (ROL_ID) REFERENCES ROL(ROL_ID)
    ) ENGINE InnoDb;

CREATE TABLE JUGADOR (
    USU_ID           VARCHAR(255) NOT NULL,
    EQU_NOMBRE       VARCHAR(255) NOT NULL,
    JUG_APP          VARCHAR(255) NOT NULL,
    JUG_APM          VARCHAR(255) NOT NULL,
    JUG_NACIMIENTO   DATE NOT NULL,
    CONSTRAINT JUG_PK PRIMARY KEY ( USU_ID,EQU_NOMBRE ),
    CONSTRAINT JUG_EQFK FOREIGN KEY ( EQU_NOMBRE ) REFERENCES EQUIPO ( EQU_NOMBRE ),
    CONSTRAINT JUG_USFK FOREIGN KEY ( USU_ID ) REFERENCES USUARIO ( USU_ID )
    ) ENGINE InnoDb;

CREATE TABLE EQUIPO (
    EQU_NOMBRE   VARCHAR(255) NOT NULL,
    IMAGEN_ID    INTEGER NOT NULL,
    ARC_ID       INTEGER NOT NULL,
    VERSION      INTEGER,
    UPPER_ID     VARCHAR(255),
    CONSTRAINT EQU_PK PRIMARY KEY ( EQU_NOMBRE ),
    CONSTRAINT EQU_IMUN UNIQUE ( IMAGEN_ID ),
    CONSTRAINT EQU_IMFK FOREIGN KEY ( ARC_ID ) REFERENCES ARCHIVO ( ARCH_ID )
    ) ENGINE InnoDb;

CREATE TABLE PARTIDO (
    PAR_ID               INTEGER NOT NULL,
    PAR_FECHA            DATE NOT NULL,
    PAR_HORA             DATE NOT NULL,
    PAR_PUNTUACION       INTEGER,
    PAR_STATUS           VARCHAR(255) NOT NULL,
    EQUIPO_NOMBRE    VARCHAR(255) NOT NULL,
    EQUIPO_NOMBRE1   VARCHAR(255) NOT NULL,
    TORNEO_ID        VARCHAR(255) NOT NULL,
    CONSTRAINT PAR_PK PRIMARY KEY ( ID )''
    CONSTRAINT PAR_EQFK FOREIGN KEY ( EQUIPO_NOMBRE ) REFERENCES EQUIPO ( EQU_NOMBRE ),
    CONSTRAINT PAR_EQFKV1 FOREIGN KEY ( EQUIPO_NOMBRE1 ) REFERENCES EQUIPO ( EQU_NOMBRE ),
    CONSTRAINT PAR_TOFK FOREIGN KEY ( TORNEO_ID ) REFERENCES TORNEO ( ID )
    ) ENGINE InnoDb;

CREATE TABLE TORNEO (
    TOR_ID           VARCHAR(255) NOT NULL,
    TOR_NOMBRE       VARCHAR(255) NOT NULL,
    TOR_FECHA        DATE NOT NULL,
    TOR_NO_EQUIPOS   INTEGER NOT NULL,
    VERSION           INTEGER,
    UPPER_ID          VARCHAR(255),
    CONSTRAINT TOR_PK PRIMARY KEY ( ID )
    ) ENGINE InnoDb;

CREATE TABLE ARCHIVO (
    ARCH_ID      INTEGER NOT NULL,
    ARCH_BYTES   LONGBLOB NOT NULL,
    VERSION      INTEGER,
    CONSTRAINT ARC_PK PRIMARY KEY ( ARCH_ID )
    ) ENGINE InnoDb;

CREATE TABLE AVISO (
    AVI_ID             VARCHAR(255) NOT NULL,
    AVI_TITULO         VARCHAR(255) NOT NULL,
    AVI_TEXTO          VARCHAR(255) NOT NULL,
    AVI_MODIFICACION   INTEGER NOT NULL,
    AVI_ELIMINADO      INTEGER NOT NULL
    CONSTRAINT AVI_TICK CHECK (AVI_TITULO <> ''),
    CONSTRAINT AVI_TXCK CHECK (AVI_TEXTO <> ''),
    CONSTRAINT AVI_PK PRIMARY KEY ( AVI_ID )
    ) ENGINE InnoDb;

INSERT INTO `usuario` (`USU_ID`, `USU_CONTRA`, `USU_NOMBRE`, `VERSION`, `UPPER_ID`) VALUES
('admin', 'Vo3i0ZGw8NSMOZ6hgkGpOdO6sYfQgn8qWm2kghGgd38=', 'Andres', 1, 'ADMIN'),
('Adycarreon', '12345', 'Adriana', 0, 'ADYCARREON'),
('Poderoso', '12345', 'Eduardo Pastor', 0, 'PODEROSO');